globals:
  file_paths:
    project_description: "/home/goku/Documentos/mlops_consulting/knowledge/sources/project_description.md"
  
    file_report_discovery: "/home/goku/Documentos/mlops_consulting/knowledge/reports/discovery_phase"
    file_report_assessment: "/home/goku/Documentos/mlops_consulting/knowledge/reports/assessment_phase"
    file_report_pipeline_design: "/home/goku/Documentos/mlops_consulting/knowledge/reports/pipeline_design_phase"
    file_report_deployment: "/home/goku/Documentos/mlops_consulting/knowledge/reports/deployment_phase"
    file_report_model_development: "/home/goku/Documentos/mlops_consulting/knowledge/reports/model_development_phase"

    file_log_discovery: "/home/goku/Documentos/mlops_consulting/mlops_consulting_flow/logs/discovery_phase"
    file_log_assessment: "/home/goku/Documentos/mlops_consulting/mlops_consulting_flow/logs/assessment_phase"
    file_log_pipeline_design: "/home/goku/Documentos/mlops_consulting/mlops_consulting_flow/logs/pipeline_design_phase"
    file_log_deployment: "/home/goku/Documentos/mlops_consulting/mlops_consulting_flow/logs/deployment_phase"
    file_log_model_development: "/home/goku/Documentos/mlops_consulting/mlops_consulting_flow/logs/model_development_phase"

    file_path_sources: "/home/goku/Documentos/mlops_consulting/knowledge/sources/"


