version: "3.8"
services:
  api:
    build:
      context: .  # Use o Dockerfile no diretório atual
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a máquina local
    volumes:
      - .:/app  # Mapeia o diretório atual para o diretório /app no container
    environment:
      - PYTHONPATH=/app:$PYTHONPATH  # Garante que o Python encontre o diretório 
    networks:
      - app-network
  n8n:
    image: n8nio/n8n  # Usando a imagem oficial do n8n
    ports:
      - "5678:5678"  # Expor a interface do n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo  # Configuração de fuso horário
    volumes:
      - n8n_data:/home/node/.n8n  # Persistência de dados do n8n
    networks:
      - app-network

volumes:
  n8n_data:

networks:
  app-network:
    driver: bridge
