# ============================================================================
# CONFIGURAÇÃO DE HIPERPARÂMETROS E QUALITY GATES
# ============================================================================
# Este arquivo centraliza TODOS os parâmetros do pipeline de ML
# Benefícios:
#   - Rastreabilidade: MLflow loga esses valores
#   - Reprodutibilidade: Mesmos params = mesmo resultado
#   - Experimentação: Fácil testar diferentes configurações
#   - Versionamento: Git versiona mudanças nos parâmetros
# ============================================================================

# ----------------------------------------------------------------------------
# HIPERPARÂMETROS DO MODELO
# ----------------------------------------------------------------------------
model:
  algorithm: RandomForest
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42
  class_weight: balanced

# ----------------------------------------------------------------------------
# DIVISÃO DE DADOS
# ----------------------------------------------------------------------------
data:
  test_size: 0.2
  random_state: 42
  stratify: true

# ----------------------------------------------------------------------------
# QUALITY GATES
# ----------------------------------------------------------------------------
metrics:
  min_accuracy: 0.75
  min_precision: 0.73
  min_recall: 0.73
  min_f1: 0.73
  max_train_test_gap: 0.10

# ----------------------------------------------------------------------------
# CROSS-VALIDATION
# ----------------------------------------------------------------------------
cv:
  n_splits: 5
  shuffle: true
  random_state: 42
